version: "2"

services:
  docker-nginx-letsencrypt-proxy:
    image: annixa/docker-nginx-letsencrypt-proxy:build
    ports:
      - 80:80
      - 443:443
    container_name: docker-nginx-letsencrypt-proxy
    log_opt:
      max-size: 50k
    environment:
      - LE_ENABLED=true
      - LE_EMAIL=andreas.drivenes@gmail.com
      - LE_DOMAIN=grafana.drivenes.net
      - PROXY_DEST=http://grafana/
    volumes:
      - "/etc/letsencrypt"
    links:
      - grafana

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
